// Subset the three typefaces and inline them as base64 woff2, so the app makes
// no network request for type in any build, including the single file one.
//
//   node scripts/build-fonts.mjs
//
// Sources are the upstream variable TTFs from the google/fonts repository, which
// are the untouched full-axis originals rather than whatever the CSS API decides
// to serve. All three are SIL Open Font License 1.1 with no Reserved Font Name,
// so subsetting and embedding is permitted; the licences are copied into
// THIRD-PARTY.md next to the code.

import { mkdir, writeFile } from 'node:fs/promises'
import { readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import subsetFont from 'subset-font'
import { cached } from './lib/fetch-cache.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = join(HERE, '..', 'src', 'assets')
const GF = 'https://raw.githubusercontent.com/google/fonts/main/ofl'

/**
 * Pairing A, "Admiralty". A Didone in the lineage of the engraved cartouches on
 * 19th century Admiralty charts, a grotesque drawn for legible small print, and
 * a wide monospace out of the teleprinter tradition.
 */
const FAMILIES = [
  {
    family: 'Bodoni Moda',
    cssName: 'Bodoni Moda',
    dir: 'bodonimoda',
    file: 'BodoniModa[opsz,wght].ttf',
    weight: '400 700',
    // Pinned to the largest optical size: this face is only ever used big.
    axes: { opsz: 72 },
  },
  {
    family: 'Archivo',
    cssName: 'Archivo',
    dir: 'archivo',
    file: 'Archivo[wdth,wght].ttf',
    weight: '300 700',
    axes: { wdth: 100 },
  },
  {
    family: 'Martian Mono',
    cssName: 'Martian Mono',
    dir: 'martianmono',
    file: 'MartianMono[wdth,wght].ttf',
    weight: '300 700',
    axes: { wdth: 100 },
  },
]

/**
 * What the app can actually display. Basic Latin, the Latin-1 supplement and
 * Latin Extended-A cover every place name in the dataset, and the tail is the
 * instrument punctuation: degree, prime, double prime, true minus, arrow.
 */
function characterSet() {
  const ranges = [
    [0x20, 0x7e],
    [0xa0, 0xff],
    [0x100, 0x17f],
    [0x2018, 0x201d],
  ]
  const singles = [0x2007, 0x2013, 0x2022, 0x2032, 0x2033, 0x2192, 0x2212, 0x2032, 0x00b0, 0x00b1, 0x00d7]
  let text = ''
  for (const [lo, hi] of ranges) {
    for (let c = lo; c <= hi; c++) text += String.fromCodePoint(c)
  }
  for (const c of singles) text += String.fromCodePoint(c)
  return text
}

const text = characterSet()
console.log(`Heliograph font pipeline: ${text.length} characters requested`)

await mkdir(OUT, { recursive: true })
const faces = []
const licences = []

for (const font of FAMILIES) {
  const encoded = font.file.replace('[', '%5B').replace(']', '%5D')
  const ttfPath = await cached(`${GF}/${font.dir}/${encoded}`, font.file.replace(/[[\]]/g, '_'))
  const licPath = await cached(`${GF}/${font.dir}/OFL.txt`, `OFL-${font.dir}.txt`)
  const source = await readFile(ttfPath)

  let subset
  try {
    subset = await subsetFont(source, text, { targetFormat: 'woff2', variationAxes: font.axes })
  } catch (error) {
    // Older subset-font builds do not know the option; the file is simply larger.
    console.log(`  ${font.family}: axis pinning unavailable (${String(error).slice(0, 60)})`)
    subset = await subsetFont(source, text, { targetFormat: 'woff2' })
  }

  const ratio = ((subset.length / source.length) * 100).toFixed(1)
  console.log(`  ${font.family.padEnd(14)} ${(source.length / 1024).toFixed(0)} KB -> ${(subset.length / 1024).toFixed(1)} KB woff2 (${ratio}%)`)

  faces.push(
    [
      '@font-face {',
      `  font-family: '${font.cssName}';`,
      '  font-style: normal;',
      `  font-weight: ${font.weight};`,
      '  font-display: block;',
      `  src: url(data:font/woff2;base64,${subset.toString('base64')}) format('woff2');`,
      '}',
    ].join('\n'),
  )
  licences.push({ family: font.family, text: await readFile(licPath, 'utf8') })
}

const header = `/*
 * Generated by scripts/build-fonts.mjs. Do not edit by hand.
 *
 * Three typefaces, subsetted to the characters this app can display and inlined
 * as base64 woff2 so nothing is fetched at runtime. All SIL Open Font License
 * 1.1; see THIRD-PARTY.md for the full texts.
 */\n\n`

await writeFile(join(OUT, 'fonts.css'), header + faces.join('\n\n') + '\n')

const thirdParty = [
  '# Third party assets',
  '',
  'Heliograph embeds three typefaces and one cartographic dataset.',
  '',
  '## Typefaces',
  '',
  'All three are licensed under the SIL Open Font License 1.1 and carry no',
  'Reserved Font Name clause, so subsetting and embedding is permitted. Full',
  'licence text: https://openfontlicense.org/open-font-license-official-text/',
  '',
  ...licences.flatMap(({ family, text: licence }) => [
    `### ${family}`,
    '',
    '```',
    licence.trim(),
    '```',
    '',
  ]),
  '## Cartography',
  '',
  'Coastlines, lakes, national boundaries, populated places and time zone',
  'polygons come from Natural Earth (https://www.naturalearthdata.com), which is',
  'in the public domain. See scripts/build-data.mjs for the exact layers used.',
  '',
].join('\n')

await writeFile(join(HERE, '..', 'THIRD-PARTY.md'), thirdParty)

const total = faces.reduce((sum, f) => sum + f.length, 0)
console.log(`\nwrote src/assets/fonts.css  ${(total / 1024).toFixed(0)} KB`)
console.log('wrote THIRD-PARTY.md')
